/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import controle.ModeloTabela;
import controle.conectaBanco;

/**
 *
 * @author nhyth
 */
public class FRM_estado extends javax.swing.JFrame {

    conectaBanco conecta = new conectaBanco();
    
    public FRM_estado() {
        initComponents();
        conecta.conexao();
        Preenchertabela("select * from estados order by id_estado ");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_estados = new javax.swing.JPanel();
        label_codigo = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_sigla = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jtf_sigla = new javax.swing.JTextField();
        jtf_nome = new javax.swing.JTextField();
        btn_sair = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_tabela = new javax.swing.JTable();
        btn_Primeiro = new javax.swing.JButton();
        btn_Ultimo = new javax.swing.JButton();
        btn_Anterior = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro_Estado");
        setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 0));

        painel_estados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painel_estados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_codigo.setText("Codigo");

        label_nome.setText("Nome");

        label_sigla.setText("Sigla");

        jtf_codigo.setToolTipText("Inserir o codigo do Estado");

        jtf_sigla.setToolTipText("Inserir a sigla do Estado");
        jtf_sigla.setMinimumSize(new java.awt.Dimension(80, 80));

        jtf_nome.setToolTipText("Inserir o nome do Estado");

        btn_sair.setText("Sair");
        btn_sair.setToolTipText("Sai do sistema Estado");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.setToolTipText("Altera informaçoes de um Estado");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.setToolTipText("Salva a inclusão de um Estado");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_deletar.setText("Delete");
        btn_deletar.setToolTipText("Deleta o estado selecionado");
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        btn_adicionar.setText("Adicionar");
        btn_adicionar.setToolTipText("Adiciona um novo Estado");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        tabela_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela_tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabela_tabela);

        btn_Primeiro.setText("Primeiro");
        btn_Primeiro.setToolTipText("Deleta o estado selecionado");
        btn_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroActionPerformed(evt);
            }
        });

        btn_Ultimo.setText("Ultimo");
        btn_Ultimo.setToolTipText("Deleta o estado selecionado");
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        btn_Anterior.setText("Anterior");
        btn_Anterior.setToolTipText("Deleta o estado selecionado");
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_proximo.setText("Proximo");
        btn_proximo.setToolTipText("Deleta o estado selecionado");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_estadosLayout = new javax.swing.GroupLayout(painel_estados);
        painel_estados.setLayout(painel_estadosLayout);
        painel_estadosLayout.setHorizontalGroup(
            painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_estadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_estadosLayout.createSequentialGroup()
                        .addGroup(painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_estadosLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_estadosLayout.createSequentialGroup()
                                        .addComponent(label_codigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_sigla)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_sigla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE))
                                    .addGroup(painel_estadosLayout.createSequentialGroup()
                                        .addComponent(label_nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(painel_estadosLayout.createSequentialGroup()
                                .addComponent(btn_adicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_deletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Primeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Ultimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_proximo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sair)))
                .addContainerGap())
        );
        painel_estadosLayout.setVerticalGroup(
            painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_estadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codigo)
                    .addComponent(label_sigla)
                    .addComponent(jtf_sigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(painel_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionar)
                    .addComponent(btn_deletar)
                    .addComponent(btn_salvar)
                    .addComponent(btn_alterar)
                    .addComponent(btn_sair)
                    .addComponent(btn_Primeiro)
                    .addComponent(btn_Ultimo)
                    .addComponent(btn_Anterior)
                    .addComponent(btn_proximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel1.setText("Formulario de cadastro de Estados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 547, Short.MAX_VALUE))
                    .addComponent(painel_estados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_estados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
      
        try {
            PreparedStatement pst = conecta.conn.prepareCall("insert into estados(nome_estado, sigla_estado)values (?,?)");
            
            
            
            
            
             pst.setString(1,jtf_nome.getText());
             pst.setString(2,jtf_sigla.getText());
             pst.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
            
           
            
            
           
             
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO NA INSERÇAO!");
        }
        
        Preenchertabela("select * from estados order by id_estado ");
        jtf_nome.setText("");
       jtf_codigo.setText("");
       jtf_sigla.setText("");
        
        
        
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
     
       try{
            PreparedStatement pst = conecta.conn.prepareStatement("delete from estados where sigla_estado = ?");
      
            
             pst.setString(1,jtf_sigla.getText());
             JOptionPane.showMessageDialog(rootPane, "excluido com sucesso");
             pst.executeUpdate();
             
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(null,"erro" +  ex);
       }
          
        
        
        
      
        
        
       jtf_nome.setText("");
       jtf_codigo.setText("");
       jtf_sigla.setText(""); 
         Preenchertabela("select * from estados order by id_estado "); 
        
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btn_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroActionPerformed

        jtf_nome.setEnabled(true);
       jtf_codigo.setEnabled(true);
       jtf_sigla.setEnabled(true);
        
        btn_alterar.setEnabled(true);
       btn_deletar.setEnabled(true);
       
       
       
        try {conecta.executaSQL("select * from estados");
            conecta.rs.first();
            jtf_codigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            jtf_nome.setText(conecta.rs.getString("nome_estado"));
            jtf_sigla.setText(conecta.rs.getString("sigla_estado"));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FRM_estado.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btn_PrimeiroActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed

         jtf_nome.setEnabled(true);
       jtf_codigo.setEnabled(true);
       jtf_sigla.setEnabled(true);
        btn_alterar.setEnabled(true);
       btn_deletar.setEnabled(true);
        
        try {conecta.executaSQL("select * from estados");
            conecta.rs.last();
            jtf_codigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            jtf_nome.setText(conecta.rs.getString("nome_estado"));
            jtf_sigla.setText(conecta.rs.getString("sigla_estado"));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FRM_estado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed

        jtf_nome.setEnabled(true);
       jtf_codigo.setEnabled(true);
       jtf_sigla.setEnabled(true); 
        
        btn_alterar.setEnabled(true);
       btn_deletar.setEnabled(true);
        
        
        
        try {
            conecta.rs.previous();
            jtf_codigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            jtf_nome.setText(conecta.rs.getString("nome_estado"));
            jtf_sigla.setText(conecta.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
            Logger.getLogger(FRM_estado.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed

         jtf_nome.setEnabled(true);
       jtf_codigo.setEnabled(true);
       jtf_sigla.setEnabled(true);
        
        
        btn_alterar.setEnabled(true);
       btn_deletar.setEnabled(true);
        
        try {
            conecta.rs.next();
            jtf_codigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            jtf_nome.setText(conecta.rs.getString("nome_estado"));
            jtf_sigla.setText(conecta.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
            Logger.getLogger(FRM_estado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
      
      try{
            PreparedStatement pst = conecta.conn.prepareStatement("update estados set nome_estado= ?,sigla_estado=? where id_estado=?");
      
             pst.setString(1,jtf_nome.getText());
             pst.setString(2,jtf_sigla.getText());
             pst.setInt(3,Integer.parseInt(jtf_codigo.getText()));
             pst.executeUpdate();
             JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso");
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(null,"erro" +  ex);
       }
        
        
        
        
        Preenchertabela("select * from estados order by id_estado ");
        
        
       jtf_nome.setText("");
       jtf_codigo.setText("");
       jtf_sigla.setText(""); 
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
       jtf_nome.setText("");
       jtf_codigo.setText("");
       jtf_sigla.setText("");
    }//GEN-LAST:event_btn_adicionarActionPerformed
public void Preenchertabela(String SQL){
    ArrayList dados = new ArrayList();
    String[] Colunas = new String[]{"ID","NOME","SIGLA"};
    conecta.executaSQL(SQL);
    
        try {
            conecta.rs.first();
            do{
                dados.add(new Object[]{conecta.rs.getInt("id_estado"),conecta.rs.getString("nome_estado"), conecta.rs.getString("sigla_estado")});
            
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro");
        }
        ModeloTabela modelo = new ModeloTabela (dados , Colunas);
        tabela_tabela.setModel(modelo);
        tabela_tabela.getColumnModel().getColumn(0).setPreferredWidth(250);
        tabela_tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela_tabela.getColumnModel().getColumn(1).setPreferredWidth(380);
        tabela_tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela_tabela.getColumnModel().getColumn(2).setPreferredWidth(120);
        tabela_tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela_tabela.getTableHeader().setReorderingAllowed(false);
        tabela_tabela.setAutoResizeMode(tabela_tabela.AUTO_RESIZE_OFF);
        tabela_tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        
}      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_estado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Primeiro;
    private javax.swing.JButton btn_Ultimo;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_sigla;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_sigla;
    private javax.swing.JPanel painel_estados;
    private javax.swing.JTable tabela_tabela;
    // End of variables declaration//GEN-END:variables
}
